version: '3.4'
services:
  frontend:
    container_name: glygen-biomarker-dev
    image: glygen-biomarker-dev:latest
    build:
      args:
        - REACT_APP_ENV=biom_dev
        - REACT_APP_BUILD=biomarker
        - REACT_APP_API=https://hivelab.biochemistry.gwu.edu/biomarker/api
        - REACT_APP_DOMAIN=https://glygen.ccrc.uga.edu/frontend
        # - REACT_APP_DOMAIN=http://localhost:6060
        - REACT_APP_BETA_DOMAIN=https://beta.glygen.org
        - REACT_APP_DATA=https://data.glygen.org
        - REACT_APP_SPARQL=https://sparql.glygen.org
        - REACT_APP_GITHUB=https://github.com/clinical-biomarkers/biomarker-partnership
        - REACT_BIOMARKER_DATA=https://hivelab.biochemistry.gwu.edu/biomarker-partnership/data
        - REACT_APP_BASENAME=/frontend
        - GENERATE_SOURCEMAP_FILES=true
        - PORT=80
    ports:
      - '80:80'
networks:
  default:
    external:
      name: glygen-network-biom-dev