version: '3.4'
services:
  frontend:
    container_name: glygen-frontend-dev
    image: glygen-frontend-dev:latest
    build:
      args:
        - REACT_APP_ENV=dev
        - REACT_APP_API=https://api.tst.glygen.org
        - REACT_APP_DOMAIN=https://glygen.ccrc.uga.edu/frontend
        # - REACT_APP_DOMAIN=http://localhost
        - REACT_APP_BETA_DOMAIN=https://beta.glygen.org
        - REACT_APP_DATA=https://data.glygen.org
        - REACT_APP_SPARQL=https://sparql.glygen.org
        - REACT_APP_BASENAME=/frontend
        - GENERATE_SOURCEMAP_FILES=true
        - PORT=80
    ports:
      - '80:80'
networks:
  default:
    external:
      name: glygen-network-dev